#!/usr/bin/env node
"use strict";

const fs = require("node:fs");

const [, , input, output, globalName] = process.argv;
if (!input || !output || !globalName) {
  console.error("usage: node tools/vendor-cjs.js <input.js> <output.js> <globalName>");
  process.exit(1);
}

const src = fs.readFileSync(input, "utf8");
const wrapped =
  `/* Vendored for archivr. Generated by tools/vendor-cjs.js. */\n` +
  `(function (global) {\n` +
  `  "use strict";\n` +
  `  var module = { exports: {} };\n` +
  `  var exports = module.exports;\n` +
  `  var require = function () { throw new Error("require() unavailable for vendored module"); };\n` +
  `  (function (module, exports, require) {\n` +
  `    ${src}\n` +
  `  })(module, exports, require);\n` +
  `  global[${JSON.stringify(globalName)}] = module.exports;\n` +
  `})(typeof globalThis !== "undefined" ? globalThis : this);\n`;
fs.writeFileSync(output, wrapped);
